apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-read-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-read
subjects:
  - kind: ServiceAccount
    name: default
    namespace: $LLMDBENCH_CLUSTER_NAMESPACE
